### ISSUE TITLE
Crashing server with dispenser

### ISSUE THREAD

**Issue by DiegoKek** [SmashMC-Development/Bugs-and-Issues#120]
You are able to crash the server by placing bone meal inside a dispenser and activating it

place bone meal inside a dispenser and activate it

tetsed on jirachi by player

Dispenser working normally and not crashing the server

n/a

check ticket #22041-found out how to crash server

**Comment by Rasgnarok** [comment]
I need a precise timestamp for the last time you tested it @DiegoKek

**Comment by Rasgnarok** [comment]
Time: 5/15/21 9:38 PM
Description: Exception in server tick loop

java.lang.IllegalStateException: Expected to be ticking over at a location! Please analyze the current phase context. 
	at org.spongepowered.common.event.tracking.TrackingUtil.lambda$throwWithContext$4(TrackingUtil.java:384)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.spongepowered.common.event.tracking.phase.tick.BlockTickPhaseState.getLocatableBlockSourceFromContext(BlockTickPhaseState.java:131)
	at org.spongepowered.common.event.tracking.phase.tick.BlockTickPhaseState.lambda$new$0(BlockTickPhaseState.java:65)
	at java.util.function.BiConsumer.lambda$andThen$0(BiConsumer.java:72)
	at org.spongepowered.common.event.SpongeCauseStackManager.checkProviders(SpongeCauseStackManager.java:160)
	at org.spongepowered.common.event.SpongeCauseStackManager.enforceMainThread(SpongeCauseStackManager.java:127)
	at org.spongepowered.common.event.SpongeCauseStackManager.popCauseFrame(SpongeCauseStackManager.java:273)
	at java.util.ArrayDeque$DeqIterator.forEachRemaining(ArrayDeque.java:674)
	at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:632)
	at org.spongepowered.common.event.tracking.PhaseTracker.ensureEmpty(PhaseTracker.java:1280)
	at net.minecraft.server.MinecraftServer.handler$zjh000$impl$completePhaseTracker(MinecraftServer.java:4528)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:713)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Rasgnarok** [comment]
Time: 5/15/21 9:36 PM
Description: Exception in server tick loop

java.lang.IllegalStateException: Cause Stack Frame Corruption! Attempted to pop a frame that was not on the stack.
	at org.spongepowered.common.event.SpongeCauseStackManager.popCauseFrame(SpongeCauseStackManager.java:297)
	at java.util.ArrayDeque$DeqIterator.forEachRemaining(ArrayDeque.java:674)
	at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:632)
	at org.spongepowered.common.event.tracking.PhaseTracker.ensureEmpty(PhaseTracker.java:1280)
	at net.minecraft.server.MinecraftServer.handler$zjh000$impl$completePhaseTracker(MinecraftServer.java:4528)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:713)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Superfire96** [comment]
Fixed
